In [2]:
# importing numpy
import numpy as np

In [ ]:
# creating a 1D array
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [13]:
# accessing elements
a[0]

array([1, 2, 3])

In [12]:
# 2D array
a = np.array([[1, 2, 3],
              [4, 5, 6]])
a.shape

(2, 3)

In [11]:
# assign different values through index
a[1] = [2,3,4]
a

array([[1, 2, 3],
       [2, 3, 4]])

In [24]:
'''
Array attributes:
-> ndim
-> shape
-> size
-> dtype
'''

a.ndim
a.shape
a.size
a.dtype

dtype('int64')

In [ ]:
'''
Array creation
-> np.zeros
-> np.ones
-> np.empty
-> np.arange
-> np.linspace
'''
# create ones array of 2 elements
new = np.ones(2)

# create range of elements from 0 to 10
new = np.arange(11)

# create range with start, stop and step
new  = np.arange(2, 8, 2)
new





array([2, 4, 6])

#### Adding, removing and sorting elements

In [5]:
'''
-> np.sort()
-> np.concatenate()
'''

'''
Different types of sorting:

-> argsort
-> lexsort
-> searchsorted
-> partition
'''

a = np.array([5,3,7,1,6])
a.sort()
a

array([1, 3, 5, 6, 7])

In [15]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

conc = np.concatenate((a, b), axis = 0)
conc

array([1, 2, 3, 4, 5, 6, 7, 8])

In [18]:
# Two 2D arrays
a = np.array([[1, 2, 3], [4, 5, 6]])  # Shape (2, 3)
b = np.array([[7, 8, 9], [10, 11, 12]])  # Shape (2, 3)

final = np.concatenate((a, b), axis = 1)
final

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [ ]:
'''
-> .ndim - 1D or 2D
-> .size - product of (x, y)
-> .shape - (x, y)
'''

#### Reshaping 

In [30]:
'''
reshape(a, newshape = (x, y))
'''
a = np.array([1,2,3,4,5,6])
a.reshape(1,6)
a

array([1, 2, 3, 4, 5, 6])

#### Convert 1D to 2D

In [19]:
import numpy as np

'''
-> np.newaxis
-> np.expand_dims
'''

a = np.array([1,2,3,4,5])
a.shape

(5,)

In [27]:
row_vector = a[np.newaxis, :]
print("Shape of row vector", row_vector.shape)
print(f"Row vector : {row_vector}")
print(a)
col_vector = a[:, np.newaxis]
print("Shape of col vector", col_vector.shape)
print(f"Col vector : {col_vector}")

Shape of row vector (1, 5)
Row vector : [[1 2 3 4 5]]
[1 2 3 4 5]
Shape of col vector (5, 1)
Col vector : [[1]
 [2]
 [3]
 [4]
 [5]]


In [31]:
b = np.expand_dims(a, axis=1)
print(f"shape of b : {b.shape}{b}")

c = np.expand_dims(a, axis=0)
print(f"shape of c : {c.shape}{c}")

shape of b : (5, 1)[[1]
 [2]
 [3]
 [4]
 [5]]
shape of c : (1, 5)[[1 2 3 4 5]]


#### Slicing and Indexing 

In [36]:
'''
-> np.nonzero()
'''

'''
in reverse, zero indexing in slicing is not considered but in normal direction, zero indexing for slicing is considered
'''

data = np.array([1,2,3])
data[-2::-1]


array([2, 1])

In [42]:
'''
special functions or operations can be done inside a[]
'''
a = np.array([[1,2,3,4], [5,6,7,8]])
print(a[a<8])

[1 2 3 4 5 6 7]


In [52]:
lessThan = np.nonzero(a < 7)
print(lessThan)

(array([0, 0, 0, 0, 1, 1]), array([0, 1, 2, 3, 0, 1]))


### Creating arrays from existing data

In [56]:
'''
-> slicing and indexing
-> np.vstack()
-> np.hstack()
-> np.hsplit()
-> .view()
-> copy()
'''

a = np.arange(0,11)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [57]:
'''
create new array from existing array using slicing
'''

new_array = a[1:9]
new_array

array([1, 2, 3, 4, 5, 6, 7, 8])

In [61]:
a1 = np.array([[1, 1],
               [2, 2]])

a2 = np.array([[3, 3],
               [4, 4]])

stacked = np.vstack((a1, a2))
stacked

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [69]:
new = np.array([1,2,3,4])
np.hsplit(new, 4)

[array([1]), array([2]), array([3]), array([4])]

In [73]:
'''
after slicing to create new array from existing array, any changes to the new array will reflect in the existing array
its a shallow copy
hence use copy() method to create a deep copy 
'''

a = np.arange(1,6)
print(f"Array 'a'  : {a}")
a_copy = a.copy()
print(f"Array 'a_copy' before change : {a_copy}")
a_copy[0] = 99
print(f"Array 'a_copy' after change : {a_copy}")
print(f"Array 'a' after change : {a}")

Array 'a'  : [1 2 3 4 5]
Array 'a_copy' before change : [1 2 3 4 5]
Array 'a_copy' after change : [99  2  3  4  5]
Array 'a' after change : [1 2 3 4 5]
