In [2]:
# importing numpy
import numpy as np

In [ ]:
# creating a 1D array
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [13]:
# accessing elements
a[0]

array([1, 2, 3])

In [12]:
# 2D array
a = np.array([[1, 2, 3],
              [4, 5, 6]])
a.shape

(2, 3)

In [11]:
# assign different values through index
a[1] = [2,3,4]
a

array([[1, 2, 3],
       [2, 3, 4]])

In [24]:
'''
Array attributes:
-> ndim
-> shape
-> size
-> dtype
'''

a.ndim
a.shape
a.size
a.dtype

dtype('int64')

In [ ]:
'''
Array creation
-> np.zeros
-> np.ones
-> np.empty
-> np.arange
-> np.linspace
'''
# create ones array of 2 elements
new = np.ones(2)

# create range of elements from 0 to 10
new = np.arange(11)

# create range with start, stop and step
new  = np.arange(2, 8, 2)
new





array([2, 4, 6])

#### Adding, removing and sorting elements

In [5]:
'''
-> np.sort()
-> np.concatenate()
'''

'''
Different types of sorting:

-> argsort
-> lexsort
-> searchsorted
-> partition
'''

a = np.array([5,3,7,1,6])
a.sort()
a

array([1, 3, 5, 6, 7])

In [15]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

conc = np.concatenate((a, b), axis = 0)
conc

array([1, 2, 3, 4, 5, 6, 7, 8])

In [18]:
# Two 2D arrays
a = np.array([[1, 2, 3], [4, 5, 6]])  # Shape (2, 3)
b = np.array([[7, 8, 9], [10, 11, 12]])  # Shape (2, 3)

final = np.concatenate((a, b), axis = 1)
final

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [ ]:
'''
-> .ndim - 1D or 2D
-> .size - product of (x, y)
-> .shape - (x, y)
'''

#### Reshaping 

In [30]:
'''
reshape(a, newshape = (x, y))
'''
a = np.array([1,2,3,4,5,6])
a.reshape(1,6)
a

array([1, 2, 3, 4, 5, 6])