In [14]:
# importing numpy
import numpy as np

In [ ]:
# creating a 1D array
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [13]:
# accessing elements
a[0]

array([1, 2, 3])

In [12]:
# 2D array
a = np.array([[1, 2, 3],
              [4, 5, 6]])
a.shape

(2, 3)

In [11]:
# assign different values through index
a[1] = [2,3,4]
a

array([[1, 2, 3],
       [2, 3, 4]])

In [24]:
'''
Array attributes:
-> ndim
-> shape
-> size
-> dtype
'''

a.ndim
a.shape
a.size
a.dtype

dtype('int64')

In [ ]:
'''
Array creation
-> np.zeros
-> np.ones
-> np.empty
-> np.arange
-> np.linspace
'''
# create ones array of 2 elements
new = np.ones(2)

# create range of elements from 0 to 10
new = np.arange(11)

# create range with start, stop and step
new  = np.arange(2, 8, 2)
new





array([2, 4, 6])